#!/bin/sh

NSENTER=$(dirname "$0")/nsenter

if [ -z "$1" ]; then
    echo "usage: docker-enter <container id/name> <command to run default:bash>"
else
    PID=$(docker inspect --format {{.State.Pid}} "$1")
    if [ -z "$PID" ]; then
        exit 1
    fi
    shift

    OPTS="--target $PID --mount --uts --ipc --net --pid -- env --ignore-environment --"

    if [ -z "$1" ]; then
        # No command given. Use su to log in to the 
        # containers default shell and set up the environment, 
        # including $HOME, $PATH etc.
        "$NSENTER" $OPTS su - root
    else
        "$NSENTER" $OPTS "$@"
    fi
fi
