#!/bin/sh
if mountpoint -q /target; then
	echo "Installing nsenter to /target"
	cp /nsenter /target
	echo "Installing docker-enter to /target"
	cp /docker-enter /target
	echo "Installing importenv to /target"
	cp /importenv /target
else
	echo "/target is not a mountpoint."
	echo "You can either:"
	echo "- re-run this container with -v /usr/local/bin:/target"
	echo "- extract the nsenter binary (located at /nsenter)"
fi
